#应用配置
server:
  port: 8383
  servlet:
    context-path: /tiantian_blog

#配置日志文件
logging:
  config: classpath:log/logback-spring.xml

spring:
  servlet:
      multipart:
                 # 上传文件总的最大值
        max-request-size: 10MB
                 # 单个文件的最大值
        max-file-size: 10MB
  profiles:
#   修改对应环境就可以使用对应的日志
    active: dev,mysql # 可切换数据库种类

  #redis配置
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: ''
    port: 6379

security:
 keypath: "C:/security"
# keypath: "/home/TianTian_J"

#mybatis plus设置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.tiantian.entity
  global-config:
    refresh: true
    banner: false
    db-config:
      #主键类型
      id-type: auto
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
